# Generated by Django 5.1.4 on 2026-07-22 10:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invigilator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Invigilator',
                'verbose_name_plural': 'Invigilators',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='LectureHall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lh_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('building', models.CharField(blank=True, max_length=255, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lecture Hall',
                'verbose_name_plural': 'Lecture Halls',
                'ordering': ['lh_code'],
            },
        ),
        migrations.CreateModel(
            name='LHMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('camera_id', models.CharField(db_index=True, max_length=100)),
                ('rtsp_url', models.CharField(max_length=512)),
                ('exam_session_label', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('invigilator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mappings', to='exam_control.invigilator')),
                ('lecture_hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mappings', to='exam_control.lecturehall')),
            ],
            options={
                'verbose_name': 'LH–Invigilator Mapping',
                'verbose_name_plural': 'LH–Invigilator Mappings',
                'ordering': ['-created_at'],
            },
        ),
    ]
