# Generated by Django 5.1.4 on 2026-07-22 13:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_file', models.FileField(upload_to='cctv_uploads/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_anomalies', models.IntegerField(default=0)),
                ('output_video_file', models.FileField(blank=True, null=True, upload_to='processed_videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_jobs', to='exam_control.lhmapping')),
            ],
            options={
                'verbose_name': 'Video Analysis Job',
                'verbose_name_plural': 'Video Analysis Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
