# Generated by Django 5.1.4 on 2026-07-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam_control", "0002_videoanalysisjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoanalysisjob",
            name="anomaly_log",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
